In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [5]:
df = pd.read_csv("Student Success & Career Path.csv")

In [6]:
df

,Student_ID,Hours_Studied,Attendance (%),Assignments_Submitted,Previous_Sem_GPA,Participation_Score,Final_Exam_Score,Pass_Fail,Career_Readiness_Score,Age,Gender
0,S001,10,85,8,3.2,70,78,Pass,65,20,Female
1,S002,5,60,5,2.5,55,55,Fail,40,21,Male
2,S003,12,90,9,3.8,80,88,Pass,75,22,Female
3,S004,3,40,3,2.0,45,45,Fail,35,19,Male
4,S005,8,75,7,3.0,65,70,Pass,60,23,Female
5,S006,6,65,6,2.7,60,60,Pass,55,20,Male
6,S007,2,30,2,1.8,40,40,Fail,25,21,Female
7,S008,11,88,9,3.5,75,82,Pass,70,22,Male
8,S009,4,50,4,2.2,50,50,Fail,45,19,Female
9,S010,9,80,8,3.1,68,75,Pass,62,20,Male
10,S011,7,72,6,2.9,63,68,Pass,58,21,Female
11,S012,1,25,1,1.5,35,35,Fail,20,19,Male
12,S013,13,92,10,3.9,85,90,Pass,80,22,Female
13,S014,6,60,5,2.6,58,58,Pass,50,20,Male
14,S015,4,45,3,2.1,48,48,Fail,38,21,Female
15,S016,10,87,8,3.4,72,80,Pass,68,23,Male
16,S017,5,55,4,2.3,52,52,Fail,42,19,Female
17,S018,12,91,9,3.7,78,85,Pass,72,22,Male
18,S019,3,35,2,1.9,42,42,Fail,30,20,Female
19,S020,9,82,8,3.2,70,77,Pass,64,21,Male

In [18]:
# DataProcessing

X = df[["Hours_Studied"]]
y = df["Final_Exam_Score"]

In [9]:
X

    Hours_Studied
0              10
1               5
2              12
3               3
4               8
5               6
6               2
7              11
8               4
9               9
10              7
11              1
12             13
13              6
14              4
15             10
16              5
17             12
18              3
19              9

In [10]:
y

0     78
1     55
2     88
3     45
4     70
5     60
6     40
7     82
8     50
9     75
10    68
11    35
12    90
13    58
14    48
15    80
16    52
17    85
18    42
19    77
Name: Final_Exam_Score, dtype: int64

In [19]:
# Train-Test Split

X_train, X_test, y_train, y_test = train_test_split(X, y , random_state = 42)

In [14]:
# Train-Model

model = LinearRegression()
model.fit(X_train, y_train)

# Evaluate Model
pred = model.predict(X_test)

In [21]:
# Rmse score and Accuracy

from sklearn.metrics import mean_squared_error, r2_score

print("MSE:", mean_squared_error(y_test, pred))
print("R2 Score:", r2_score(y_test, pred))

MSE: 2.7549670721449298
R2 Score: 0.9864046236076544

In [16]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LinearRegression())
])

In [17]:
pipe

Pipeline(steps=[('scaler', StandardScaler()), ('model', LinearRegression())])